import type { CatalogGame } from '../../domain/catalog-game.js'

export const catalogReferenceGames: CatalogGame[] = [
  {
    definition: {
      gameId: 'signal-grid',
      slug: 'signal-grid',
      status: 'active',
      tags: ['board', 'ranked', 'dedicated-server'],
      category: 'board',
      categoryKey: 'navigation.categories.board',
      displayNameKey: 'catalog.gameMeta.names.signal-grid',
      descriptionKey: 'catalog.gameMeta.descriptions.signal-grid',
      taglineKey: 'catalog.gameMeta.tagline.signal-grid',
    },
    activeVersion: {
      gameVersion: '0.1.0-prototype',
      protocolVersion: 'v1',
      buildVersion: 'prototype',
      runtime: {
        clientRuntime: 'web',
        engine: 'prototype-dom',
        serverType: 'dedicated',
      },
      capabilities: {
        multiplayer: true,
        ranked: true,
        spectators: true,
        replays: false,
        privateRooms: true,
      },
      platforms: {
        web: true,
        windows: true,
        macos: true,
        android: false,
        ios: false,
        ipados: false,
      },
      distribution: {
        minimumVersion: '0.1.0',
        downloadStrategy: 'browser',
        launchStrategy: 'route',
        architecture: 'browser',
      },
    },
  },
  {
    definition: {
      gameId: 'rush-lane',
      slug: 'rush-lane',
      status: 'active',
      tags: ['arcade', 'shared-runtime', 'quick-play'],
      category: 'arcade',
      categoryKey: 'navigation.categories.arcade',
      displayNameKey: 'catalog.gameMeta.names.rush-lane',
      descriptionKey: 'catalog.gameMeta.descriptions.rush-lane',
      taglineKey: 'catalog.gameMeta.tagline.rush-lane',
    },
    activeVersion: {
      gameVersion: '0.1.0-prototype',
      protocolVersion: 'v1',
      buildVersion: 'prototype',
      runtime: {
        clientRuntime: 'web',
        engine: 'prototype-canvas',
        serverType: 'shared',
      },
      capabilities: {
        multiplayer: true,
        ranked: false,
        spectators: false,
        replays: false,
        privateRooms: true,
      },
      platforms: {
        web: true,
        windows: true,
        macos: true,
        android: true,
        ios: true,
        ipados: true,
      },
      distribution: {
        minimumVersion: '0.1.0',
        downloadStrategy: 'browser',
        launchStrategy: 'route',
        architecture: 'browser',
      },
    },
  },
  {
    definition: {
      gameId: 'aether-flight',
      slug: 'aether-flight',
      status: 'active',
      tags: ['simulation', '3d', 'mission-bay'],
      category: 'simulation',
      categoryKey: 'navigation.categories.simulation3d',
      displayNameKey: 'catalog.gameMeta.names.aether-flight',
      descriptionKey: 'catalog.gameMeta.descriptions.aether-flight',
      taglineKey: 'catalog.gameMeta.tagline.aether-flight',
    },
    activeVersion: {
      gameVersion: '0.1.0-prototype',
      protocolVersion: 'v1',
      buildVersion: 'prototype',
      runtime: {
        clientRuntime: 'web',
        engine: 'prototype-threejs-preview',
        serverType: 'dedicated',
      },
      capabilities: {
        multiplayer: true,
        ranked: false,
        spectators: false,
        replays: false,
        privateRooms: true,
      },
      platforms: {
        web: true,
        windows: true,
        macos: true,
        android: false,
        ios: false,
        ipados: false,
      },
      distribution: {
        minimumVersion: '0.1.0',
        downloadStrategy: 'browser',
        launchStrategy: 'route',
        architecture: 'browser',
      },
    },
  },
]