http:
  routers:
    api:
      entryPoints:
        - web
      rule: PathPrefix(`/api`) || PathPrefix(`/health`)
      service: platform-api
    realtime:
      entryPoints:
        - web
      rule: PathPrefix(`/realtime/v1/ws`)
      service: realtime-gateway
    web:
      entryPoints:
        - web
      rule: PathPrefix(`/`)
      service: web

  services:
    platform-api:
      loadBalancer:
        servers:
          - url: http://platform-api:3000
    realtime-gateway:
      loadBalancer:
        servers:
          - url: http://realtime-gateway:8081
    web:
      loadBalancer:
        servers:
          - url: http://web:80