http:
  routers:
    api:
      entryPoints:
        - web
      rule: PathPrefix(`/api`) || PathPrefix(`/health`)
      service: platform-api
    web:
      entryPoints:
        - web
      rule: PathPrefix(`/`)
      service: web

  services:
    platform-api:
      loadBalancer:
        servers:
          - url: http://platform-api:3000
    web:
      loadBalancer:
        servers:
          - url: http://web:5173